[ERROR] 2025-04-16 10:39:27.022 [restartedMain] SqlExceptionHelper  - Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
[ERROR] 2025-04-16 10:39:27.030 [restartedMain] LocalContainerEntityManagerFactoryBean  - Failed to initialize JPA EntityManagerFactory: Unable to create requested service [org.hibernate.engine.jdbc.env.spi.JdbcEnvironment] due to: Unable to resolve name [org.hibernate.dialect.PostgresDialect] as strategy [org.hibernate.dialect.Dialect]
[ERROR] 2025-04-16 10:39:27.065 [restartedMain] SpringApplication org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaConfiguration.class]: Unable to create requested service [org.hibernate.engine.jdbc.env.spi.JdbcEnvironment] due to: Unable to resolve name [org.hibernate.dialect.PostgresDialect] as strategy [org.hibernate.dialect.Dialect]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1812) - Application run failed
[ERROR] 2025-04-16 10:42:35.163 [restartedMain] SqlExceptionHelper  - Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
[ERROR] 2025-04-16 10:42:35.172 [restartedMain] LocalContainerEntityManagerFactoryBean  - Failed to initialize JPA EntityManagerFactory: Unable to create requested service [org.hibernate.engine.jdbc.env.spi.JdbcEnvironment] due to: Unable to resolve name [org.hibernate.dialect.PostgresDialect] as strategy [org.hibernate.dialect.Dialect]
[ERROR] 2025-04-16 10:42:35.206 [restartedMain] SpringApplication org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaConfiguration.class]: Unable to create requested service [org.hibernate.engine.jdbc.env.spi.JdbcEnvironment] due to: Unable to resolve name [org.hibernate.dialect.PostgresDialect] as strategy [org.hibernate.dialect.Dialect]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1812) - Application run failed
[ERROR] 2025-04-16 10:42:51.883 [restartedMain] SqlExceptionHelper  - Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
[ERROR] 2025-04-16 10:42:51.891 [restartedMain] LocalContainerEntityManagerFactoryBean  - Failed to initialize JPA EntityManagerFactory: Unable to create requested service [org.hibernate.engine.jdbc.env.spi.JdbcEnvironment] due to: Unable to resolve name [org.hibernate.dialect.PostgresDialect] as strategy [org.hibernate.dialect.Dialect]
[ERROR] 2025-04-16 10:42:51.923 [restartedMain] SpringApplication org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaConfiguration.class]: Unable to create requested service [org.hibernate.engine.jdbc.env.spi.JdbcEnvironment] due to: Unable to resolve name [org.hibernate.dialect.PostgresDialect] as strategy [org.hibernate.dialect.Dialect]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1812) - Application run failed
[ERROR] 2025-04-16 10:48:55.805 [restartedMain] SpringApplication org.springframework.context.ApplicationContextException: Failed to start bean 'webServerStartStop'
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:326) - Application run failed
[ERROR] 2025-04-16 11:05:22.587 [http-nio-48080-exec-4] SqlExceptionHelper  - Table "members" not found (this database is empty); SQL statement:
select count(*) from members m1_0 [42104-232]
[ERROR] 2025-04-16 11:05:22.601 [http-nio-48080-exec-4] [dispatcherServlet] org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "members" not found (this database is empty); SQL statement:
select count(*) from members m1_0 [42104-232]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:514) - Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed: org.springframework.dao.InvalidDataAccessResourceUsageException: could not prepare statement [Table "members" not found (this database is empty); SQL statement:
select count(*) from members m1_0 [42104-232]] [select count(*) from members m1_0]; SQL [select count(*) from members m1_0]] with root cause
[ERROR] 2025-04-16 11:05:53.057 [http-nio-48080-exec-9] SqlExceptionHelper  - Table "members" not found (this database is empty); SQL statement:
select count(*) from members m1_0 [42104-232]
[ERROR] 2025-04-16 11:05:53.059 [http-nio-48080-exec-9] [dispatcherServlet] org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "members" not found (this database is empty); SQL statement:
select count(*) from members m1_0 [42104-232]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:514) - Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed: org.springframework.dao.InvalidDataAccessResourceUsageException: could not prepare statement [Table "members" not found (this database is empty); SQL statement:
select count(*) from members m1_0 [42104-232]] [select count(*) from members m1_0]; SQL [select count(*) from members m1_0]] with root cause
[ERROR] 2025-04-16 15:19:22.591 [http-nio-48080-exec-5] [dispatcherServlet] org.hibernate.id.IdentifierGenerationException: Identifier of entity 'io.iteyes.genaicodebooster.domain.member.entity.Member' must be manually assigned before calling 'persist()'
	at org.hibernate.event.internal.AbstractSaveEventListener.performSave(AbstractSaveEventListener.java:208) - Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed: org.springframework.orm.jpa.JpaSystemException: Identifier of entity 'io.iteyes.genaicodebooster.domain.member.entity.Member' must be manually assigned before calling 'persist()'] with root cause
[ERROR] 2025-04-16 15:19:35.954 [http-nio-48080-exec-6] [dispatcherServlet] org.hibernate.id.IdentifierGenerationException: Identifier of entity 'io.iteyes.genaicodebooster.domain.member.entity.Member' must be manually assigned before calling 'persist()'
	at org.hibernate.event.internal.AbstractSaveEventListener.performSave(AbstractSaveEventListener.java:208) - Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed: org.springframework.orm.jpa.JpaSystemException: Identifier of entity 'io.iteyes.genaicodebooster.domain.member.entity.Member' must be manually assigned before calling 'persist()'] with root cause
[ERROR] 2025-04-16 15:47:41.413 [http-nio-48080-exec-5] [dispatcherServlet] org.hibernate.id.IdentifierGenerationException: Identifier of entity 'io.iteyes.genaicodebooster.domain.member.entity.Member' must be manually assigned before calling 'persist()'
	at org.hibernate.event.internal.AbstractSaveEventListener.performSave(AbstractSaveEventListener.java:208) - Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed: org.springframework.orm.jpa.JpaSystemException: Identifier of entity 'io.iteyes.genaicodebooster.domain.member.entity.Member' must be manually assigned before calling 'persist()'] with root cause
[ERROR] 2025-04-16 15:48:22.522 [http-nio-48080-exec-1] [dispatcherServlet] org.hibernate.id.IdentifierGenerationException: Identifier of entity 'io.iteyes.genaicodebooster.domain.member.entity.Member' must be manually assigned before calling 'persist()'
	at org.hibernate.event.internal.AbstractSaveEventListener.performSave(AbstractSaveEventListener.java:208) - Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed: org.springframework.orm.jpa.JpaSystemException: Identifier of entity 'io.iteyes.genaicodebooster.domain.member.entity.Member' must be manually assigned before calling 'persist()'] with root cause
[ERROR] 2025-04-16 19:17:37.921 [http-nio-48080-exec-7] AiService java.lang.NullPointerException: Cannot invoke "org.springframework.web.client.RestTemplate.postForEntity(String, Object, java.lang.Class, Object[])" because "this.restTemplate" is null
	at io.iteyes.genaicodebooster.api.service.AiService.sendMessage(AiService.java:27) - AI 서버 호출 실패
[ERROR] 2025-04-16 19:17:59.536 [http-nio-48080-exec-3] AiService java.lang.NullPointerException: Cannot invoke "org.springframework.web.client.RestTemplate.postForEntity(String, Object, java.lang.Class, Object[])" because "this.restTemplate" is null
	at io.iteyes.genaicodebooster.api.service.AiService.sendMessage(AiService.java:27) - AI 서버 호출 실패
[ERROR] 2025-04-16 19:21:38.179 [http-nio-48080-exec-6] AiService org.springframework.web.client.ResourceAccessException: I/O error on POST request for "http://localhost:8000/ask": Read timed out
	at org.springframework.web.client.RestTemplate.createResourceAccessException(RestTemplate.java:926) - AI 서버 호출 실패
[ERROR] 2025-04-16 19:22:19.091 [http-nio-48080-exec-9] SqlExceptionHelper  - NULL not allowed for column "message"; SQL statement:
insert into chats (chat_room_id,created_at,message,sender_type,id) values (?,?,?,?,default) [23502-232]
[ERROR] 2025-04-16 19:22:19.136 [http-nio-48080-exec-9] ChatController org.springframework.dao.DataIntegrityViolationException: could not execute statement [NULL not allowed for column "message"; SQL statement:
insert into chats (chat_room_id,created_at,message,sender_type,id) values (?,?,?,?,default) [23502-232]] [insert into chats (chat_room_id,created_at,message,sender_type,id) values (?,?,?,?,default)]; SQL [insert into chats (chat_room_id,created_at,message,sender_type,id) values (?,?,?,?,default)]; constraint [null]
	at org.springframework.orm.jpa.vendor.HibernateJpaDialect.convertHibernateAccessException(HibernateJpaDialect.java:290) - 채팅 생성 중 오류 발생
[ERROR] 2025-04-16 19:40:24.568 [http-nio-48080-exec-3] AiService org.springframework.web.client.ResourceAccessException: I/O error on POST request for "http://localhost:8000/ask": Read timed out
	at org.springframework.web.client.RestTemplate.createResourceAccessException(RestTemplate.java:926) - AI 서버 호출 실패
